#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

# rules
bspc rule -a mpv state=floating
bspc rule -a feh state=floating
bspc rule -a firefox desktop='^2'
bspc rule -a Spotify desktop='^3'

# workspaces
bspc monitor -d 1 2 3 4

# window gaps/borders
bspc config border_width 3
bspc config window_gap 10
bspc config focused_border_color "#7899FA"
bspc config normal_border_color "#1f222b"

# float window
bspc config split_ratio 0.5
bspc config focus_follows_pointer true
bspc config pointer_modifier super

# fix cursor
xsetroot -cursor_name left_ptr &
# disable sleep mode
xset s off -dpms
# keymaps
setxkbmap us,ru -option "grp:alt_shift_toggle"

# set display resolution
$HOME/.config/bspwm/resol.sh
# polybar
$HOME/.config/polybar/launch.sh &

# apps
telegram-desktop -startintray &
dunst &
flameshot &
